name: Pull Request Control

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Check branch name
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          if [[ ${{ github.event.pull_request.base.ref }} == "master" && ${{ github.event.pull_request.head.ref }} != "testing" ]]; then
            echo "Pull requests can only be merged from 'testing' into 'master'."
            exit 1
          fi
        fi
